name: Wiki Deployment

on:
  push:
    branches:
      - trunk
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-to-wiki.yml'

jobs:
  sync-wiki-files:
    name: Sync Wiki Files

    runs-on: ubuntu-latest

    steps:
      - name: Checkout /docs
        uses: actions/checkout@v2

      - name: Checkout wiki files
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki 
          path: tmp

      - name: Sync wiki files
        run: |
          rsync -avzr --delete --exclude='.git/' "docs/" "tmp/" || exit 1

      - name: Commit wiki files
        working-directory: ${{github.repository}}/tmp
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Synchronize wiki with docs/"

      - name: Push changes to wiki
        uses: ad-m/github-push-action@master
        with:
          directory: ${{runner.workspace}}/${{github.repository}}/tmp
          repository: ${{github.repository}}.wiki
