name: Wiki Deployment

on:
  push:
    branches:
      - trunk
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-to-wiki.yml'

jobs:
  sync-wiki-files:
    name: Sync Wiki Files

    runs-on: ubuntu-latest

    steps:
      - name: Checkout /docs
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          path: main

      - name: Checkout wiki files
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Sync wiki files
        run: |
          for docname in main/docs/*.md; do
            old=$(basename $docname);
            new=${old%.*};
            for docpath in main/docs/*.md; do
              sed "s/$old/$new/" $docpath;
            done
          done
          rsync -avzr --delete --exclude='.git/' "main/docs/" "wiki/"

      - name: Commit wiki files
        working-directory: wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Synchronize wiki with docs/"

      - name: Push changes to wiki
        uses: ad-m/github-push-action@master
        with:
          directory: wiki
          repository: ${{github.repository}}.wiki
          branch: master
